export default defineAppConfig({
  ui: {
    container: {
      base: 'max-w-4xl',
    },
    colors: {
      primary: 'neutral',
      white: 'white',
      black: 'black',
      neutral: 'neutral',
      red: 'red',
      green: 'green',
      blue: 'blue',
      yellow: 'yellow',
      purple: 'purple',
      pink: 'pink',
      indigo: 'indigo',
      cyan: 'cyan',
      teal: 'teal',
      gray: 'gray',
      orange: 'orange',
      amber: 'amber',
      lime: 'lime',
      emerald: 'emerald',
      rose: 'rose',
      sky: 'sky',
      violet: 'violet',
      fuchsia: 'fuchsia',
      lightBlue: 'lightBlue',
    },
  },
})
